---
title: "Predicting Anxiety Diagnosis from Survey Data"
author: "Wayne Huynh"
date: "2023-08-09"
output: html_document
---

``` {r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

``` {r, include=FALSE}
#Install the necessary packages to run the rest of the file
install.packages("tidyverse")
install.packages("lm.beta")
install.packages("magrittr") 
install.packages("dplyr")
install.packages("ggplot2")
```

``` {r, include=FALSE}
library("magrittr")
library("dplyr") 
library("ggplot2")
```

``` {r, include=FALSE}
#Import survey data
data <- read.csv('BRFSS2015_650.csv')
```

``` {r}
#I am looking to find the relationship between people who have been diagnosed with anxiety vs their veteran status, height and weight.
#Anxiety diagnosis(ADANXEV) is my response variable
#Veteran status(VETERAN3), height(HEIGHT3), and weight(WEIGHT2) are my predictor variables

#Anxiety diagnosis(ADANXEV) and Veteran status(VETERAN3) won't have outliers since they are yes/no
#I will choose to not remove any outliers because part of my project will be seeing if extreme heights and weights contribute to an anxiety diagnosis

```


``` {r}
#Clean data
#Anxiety diagnosis(ADANXEV)
#Only keep people who answered Yes(1) or No(2)
data <- subset(data, ADANXEV == 1 | ADANXEV == 2)

#Veteran status(VETERAN3)
#Only keep people who answered Yes(1) or No(2)
data <- subset(data, VETERAN3 == 1 | VETERAN3 == 2)

#Height(HEIGHT3)
#Only keep people with a reported height (200-711) and (9000-9998)
data <- subset(data, (HEIGHT3 >=200 & HEIGHT3 <=711) | (HEIGHT3 >= 9000 & HEIGHT3 <= 9998))

#Convert reported heights to inches
to_in <- function(number) {
  result <-
    #convert ft/in to in
    ifelse(number >= 200 & number <= 711,
           (number %/% 100) * 12 + (number %% 100),
           #convert 9/m/cm to cm then to in
           ifelse(number >= 9000 & number <= 9998,
                  round(0.393701*(number %% 1000),0),
                  number))
  return(result)
}

#Apply the to_in function to the HEIGHT3 column
data <- data %>%
  mutate(HEIGHT = to_in(HEIGHT3))


#Weight(WEIGHT3)
#Only keep people with a reported weight (50-0999) and (9000-9998)
data <- subset(data, (WEIGHT2 >=50 & WEIGHT2 <=999) | (WEIGHT2 >= 9000 & WEIGHT2 <= 9998))

#Convert reported weights from kilograms to pounds
to_lbs <- function(number) {
  result <-
    #convert kgs to lbs
    ifelse(number >= 9000 & number <= 9998,
           round(2.20462262185*(number %% 1000),0),
           number)
  return(result)
}
#Apply the to_lbs function to the WEIGHT2 column
data <- data %>%
  mutate(WEIGHT = to_lbs(WEIGHT2))
```


``` {r}
ggplot(data) +
  geom_boxplot(mapping = aes(HEIGHT))
#There are 4 low outliers and 6 higher outliers in terms of height, but overall it seems decently normally distributed
```


``` {r}
ggplot(data) +
  geom_boxplot(mapping = aes(WEIGHT))
#The weight distribution is right-skewed
```


``` {r}
ggplot(data) +
  geom_point(aes(x = WEIGHT, y = HEIGHT, color = VETERAN3))
#This plot shows people's height/weight measurement color coded by their Veteran status
#Black is a veteran, blue is not
#Veterans' height/weight measurements are mostly in the middle of the plot
```


``` {r}
ggplot(data) +
  geom_point(aes(x = WEIGHT, y = HEIGHT, color = ADANXEV))
#This plot shows people's height/weight measurement color coded by their anxiety diagnosis
#Black has anxiety, blue does not
#Initially, it does seem like there are more people with anxiety in the bottom right area
#This shows roughly that shorter people and heavier people tend to have anxiety more often than taller and/or light people
```


``` {r}
ggplot(data = data) +
  geom_point(mapping = aes(x = WEIGHT, y = HEIGHT)) +
  facet_grid(ADANXEV ~ VETERAN3)
#1 on the right = anxiety, 2 on the right = no anxiety diagnosis
#1 on top = veteran, 2 on top = not a veteran
#This confirms that veterans look much more alike each other in terms of height/weight than non-veterans
#It also shows that anxiety diagnoses are slightly more spread out from the big cluster than non-anxiety diagnoses
```


``` {r}
#Calculate the proportion of anxiety diagnoses within each veteran status
summary_data <- data %>%
  group_by(VETERAN3, ADANXEV) %>%
  summarise(proportion = n()) %>%
  ungroup() %>%
  mutate(proportion = proportion / sum(proportion))

# Create a percent stacked bar plot
ggplot(summary_data, aes(x = VETERAN3, y = proportion, fill = ADANXEV)) +
  geom_bar(position = "fill", stat = "identity") +
  labs(x = "Veteran Status", y = "Proportion", fill = "Anxiety") +
  ggtitle("Proportion of Anxiety Levels by Veteran Status")
#Veteran = 1 means veteran; Veteran = 2 means not a veteran
#Anxiety = 1 or black means diagnosed anxiety; Anxiety = 2 or blue means no anxiety diagnosis
#This plot shows that veterans (left side) have a slightly lower anxiety proportion than the non-veteran group (right side)
#We do not know if this difference is significant though
```


``` {r}
data$ADANXEV1 <- factor(data$ADANXEV)
ggplot(data = data, mapping = aes(x = WEIGHT, y = HEIGHT, color = VETERAN3)) +
  geom_point() +
  geom_smooth(mapping = aes(linetype = ADANXEV1))
#ADANXEV1 = 1 means anxiety; ADANXEV1 = 2 means no anxiety diagnosis
#The anxiety trendline is lower which might signal that shorter people get diagnosed with anxiety more
#Because veterans look to be taller on average than a non-veteran, this also might signal that veterans get diagnosed with anxiety less than a non-veteran
```


```{r}
#Anxiety diagnosis(ADANXEV)
#Calculate descriptive statistics of 'ADANXEV'
summary(data$ADANXEV)
#1st quartile is 2 indicating an overwhelming majority of people are not diagnosed with anxiety

#Count of people with (1) and without (2) anxiety diagnosis
table(data$ADANXEV)
#With: 3,145 people
#Without: 15,982 people
```


```{r}

```


```{r}
#Veteran status(VETERAN3)
#Calculate descriptive statistics of 'VETERAN3'
summary(data$VETERAN3)
#1st quartile is 2 indicating an overwhelming majority of people are not veterans

#Count of veterans (1) and non-veterans (2)
table(data$VETERAN3)
#Veterans: 2,585 people
#Non-veterans: 16,542 people
```


``` {r}
#Height(HEIGHT)
#Calculate descriptive statistics of 'HEIGHT'
summary(data$HEIGHT)
#Shortest person is 48in (4')
#Median person is 66in (5'6")
#Tallest person is 85in (7'1")

table(data$HEIGHT)
#There are relatively few people shorter than 60in (5') or taller than 74in (6'2") which is true of American society so this height dataset feels valid
```


``` {r}
#Weight (WEIGHT)
#Calculate descriptive statistics of 'WEIGHT'
summary(data$WEIGHT)
#Lightest person is 61lbs
#Median person is 179lbs
#Heaviest person is 680lbs

#Count of veterans (1) and non-veterans (2)
table(data$WEIGHT)
#Most people reported weights that are divisible by 5
#There are relatively few people that weigh less than 100lbs or more than 300lbs which is generally true of America
```


``` {r}
#ADANXEV has to be 0 and 1 for the logistic regression to run
data$ANXIETY <- ifelse(data$ADANXEV == 2, 1, 0)
```


``` {r}
#Logistic regression of how height and weight affect anxiety diagnosis frequency
model1 <- glm(ANXIETY ~ HEIGHT + WEIGHT, data = data, family = binomial)
# Display the summary of the logistic regression model
summary(model1)
```


```{r}
#Logistic regression of how height and weight and veteran status affect anxiety diagnosis frequency
model2 <- glm(ANXIETY ~ HEIGHT + WEIGHT + VETERAN3, data = data, family = binomial)
# Display the summary of the logistic regression model
summary(model2)
```


``` {r}
#Logistic regression of how height and veteran status affect anxiety diagnosis frequency
model3 <- glm(ANXIETY ~ HEIGHT + VETERAN3, data = data, family = binomial)
# Display the summary of the logistic regression model
summary(model3)
```


``` {r}
#Logistic regression of how weight and veteran status affect anxiety diagnosis frequency
model4 <- glm(ANXIETY ~ WEIGHT + VETERAN3, data = data, family = binomial)
# Display the summary of the logistic regression model
summary(model4)
```


``` {r}
model1$aic
#16941.43

model2$aic
#16936.19

model3$aic
#17000.64

model4$aic
#17062.32
```


``` {r}
#Model 2 has the lowest AIC value so it is likely to be the best fit model

#The HEIGHT coefficient signals that for every 1" increase in HEIGHT, the log-odds of having an anxiety diagnosis increases by 0.0637003.
#HEIGHT is statistically significant with a P-value below 0.05 and the relationship is unlikely to be from random chance alone
#This does not line up with my prediction from the previous visualizations where I assumed that shorter people would be diagnosed with anxiety more
#This could be because there are more shorter people, so it seems like there are more anxiety diagnoses initially at the bottom, but the proportion of taller people having anxiety could be higher. But that is somewhat hard to discern off a visualization with thousands of data points

#The WEIGHT coefficient signals that for every 1lb increase in WEIGHT, the log-odds of having an anxiety diagnosis decreases by 0.0037462.
#WEIGHT is statistically significant with a P-value below 0.05 and the relationship is unlikely to be from random chance alone
#This does line up with my prediction that heavier people are more likely to have an anxiety diagnosis.

#The VETERAN3 coefficient signals that for every 1 unit increase in VETERAN3 (from yes to no), the log-odds of having an anxiety diagnosis decreases by 0.1728791.
#VETERAN3 is statistically significant with a P-value below 0.05 and the relationship is unlikely to be from random chance alone
#This does not line up with one of the visualizations showing that anxiety diagnosis rate increases from a veteran to a non-veteran
```


``` {r}
model2.chi <- model2$null.deviance - model2$deviance

model2.df <- model2$df.null - model2$df.residual
cat("p-value = ", 1-pchisq(model2.chi, model2.df))
#p-value =  0
#A p-value < 0.05 means the observed Chi-square difference is unlikely to have occurred by random chance alone
```


``` {r}

cat("Chi-square difference = ", model2.chi)
#Chi-square difference =  169.0151
#169.0151 is the difference in deviances between the null model and Model 2, which includes all of the predictor variables (HEIGHT, WEIGHT, and VETERAN3)
#This is a relatively high Chi-square difference meaning that adding more predictor variables will improve my model fit in a logistic regression model
```

